version: "3"

services:

  app:
    container_name: app
    build: .
    ports:
      - 8082:3001
    volumes:
      - .:/home/app
    depends_on:
      - pg
    env_file:
      - .env

  pg:
    container_name: pg
    image: postgres:14.5
    restart: always
    ports:
      - 5544:5432
    env_file:
      - .env
    volumes:
      - vol_pg:/var/lib/postgresql/
  
volumes:
  vol_pg:
